### ISSUE TITLE
Severe error (java)

### ISSUE THREAD

**Issue by referup-tarantegui** [s12v/newrelic-elasticsearch-docker#2]
It seems that container runs ok but after a wait of several minutes nothing shown on newrelic plugins. This is the output of the container logs.

```
[09:46:12] [INFO] operations - Generating 'newrelic.json' file for plugin...
[09:46:12] [INFO] operations - Running in 'noedit' mode, not opening plugin configuration file.
Trying elasticsearch:9200... OK
[09:46:12] [INFO] operations - Starting plugin 'me.snov.newrelic-elasticsearch' in foreground...
[09:46:12] [INFO] operations - Please visit https://rpm.newrelic.com to verify that the plugin is successfully reporting to your account. It may take a few minutes to become visible.
INFO: Using configuration file /root/newrelic-npi/plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-1.6.1/config/newrelic.json
INFO: Using configuration file /root/newrelic-npi/plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-1.6.1/config/plugin.json
INFO: New Relic monitor started
SEVERE: An error has occurred
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 2329 path $.nodes..os.load_average
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
    at com.google.gson.Gson.fromJson(Gson.java:810)
    at com.google.gson.Gson.fromJson(Gson.java:748)
    at me.snov.newrelic.elasticsearch.parsers.AbstractParser.parse(Unknown Source)
    at me.snov.newrelic.elasticsearch.parsers.AbstractParser.request(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.pollCycle(Unknown Source)
    at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 2329 path $.nodes..os.load_average
    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:79)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
    ... 20 more
```

**Comment by s12v** [comment]
Elasticsearch 2.x? It's fixed in https://github.com/s12v/newrelic-elasticsearch/releases/tag/2.0.0, I've rebuilt container on docker hub.

Should work now.

**Comment by referup-tarantegui** [comment]
Thanks a lot. It works smoothly now. Issue solved!

2015-12-23 21:48 GMT+01:00 Sergey Novikov notifications@github.com:
